Diplom3
moiseenko-e/QA-java-diplom-3 pull request #1
Opened 2023-06-25 16:06 UTC by moiseenko-e

2023-06-26 14:10 UTC, pavel-ulan requested changes
Тут как-то похуже. Есть неправильные тесты, проверки в остальных с хардкодом, что недопустимо. В общем в этом задании работы будет побольше.

2023-06-26 14:10 UTC, pavel-ulan commented on src/main/java/praktikum/pageobject/LoginPage.java
> +    private final By forgotPasswordButton = By.xpath("/html/body/div[1]/div/main/div/div/p[2]/a"); // проверен
**можно лучше**
очень очень некрасивый локатор, состоящий из абсолютного пути =/
Старайся не использовать локаторы состоящие только из пути (не важно относительный/абсолютный). Как правило всегда можно подобрать другой, более читаемый, локатор. Такие локаторы плохо читаются, по ним непонятно, куда они указывают и если что-то меняется в верстке, то они ломаются и могут или никуда не вести или, что еще хуже, возвращать совершенно другой элемент.

2023-06-26 14:10 UTC, pavel-ulan commented on src/main/java/praktikum/pageobject/LoginPage.java
> +    private final By enterGetText = By.xpath("//h2[contains(text(),'Вход')]"); // проверен
**можно лучше**
а локаторы использующие текст могут не работать если у тебя есть несколько локализаций =)
(тут это не актуально, но просто знай)

2023-06-26 14:10 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        // driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
?

2023-06-26 14:10 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        objloginPage.login("test0202@yandex.ru", "012345");
**можно лучше**
хардкодишь тестовые данные

2023-06-26 14:10 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
**надо исправить**
а вот тут хардкод вообще недопустим (и нелогичен если честно).
У тебя есть какое-то значение, по которому ты определяешь прошел тест или нет. Логично или вынести это в константу класса как VALID_что-то или (что еще лучше) зашить это в классе шагов или PO как проверку на валидность, т.к. по сути это константное значение для страницы (это не номер заказа или ID пользователя который может меняться, а постоянное поле).

2023-06-26 14:10 UTC, pavel-ulan commented on src/test/java/praktikum/MainPageTests.java
> +        assertThat(newBreadText, is("Булки"));
**надо исправить**
А тут у тебя вообще тест работает неправильно. (хотя это неочевидно, но если ты проскролишь после перехода к разделу в дебаге и остановишь выполнение, а потом перейдешь в другой раздел, то после продолжения исполнения тест пройдет).
В общем ты проверяешь текст в разделах, но метод проверки на самом деле считает, что текст виден, даже если он проскролен, т.к. этот метод проверяет что у локатора отсутствует свойство hidden.

Попробуй проскролить разделы и смотреть как меняются имена классов в верстке у разделов. И построй проверку "в каком разделе я нахожусь" на этой основе.

2023-06-29 11:03 UTC, moiseenko-e commented on src/main/java/praktikum/pageobject/LoginPage.java
> +    private final By forgotPasswordButton = By.xpath("/html/body/div[1]/div/main/div/div/p[2]/a"); // проверен
исправила

2023-06-29 11:06 UTC, moiseenko-e commented on src/test/java/praktikum/LoginPageTest.java
> +        // driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
исправила

2023-07-02 19:48 UTC, moiseenko-e commented on src/test/java/praktikum/MainPageTests.java
> +        assertThat(newBreadText, is("Булки"));
исправила указанный тест

2023-07-02 19:49 UTC, moiseenko-e commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
исправила, вынесла в константу

2023-07-04 17:32 UTC, pavel-ulan requested changes
У тебя обе ветки слились в одну. Часть тестов задублировалась, соответственно часть старых и часть новых. Разберись с коммитом пожалуйста.

2023-07-04 17:32 UTC, pavel-ulan commented on MainPageTests.java
> +        assertThat(attributeValue, containsString("tab_tab_type_current"));
**надо исправить**
уже лучше. Но у тебя остался прошлый assert, который по сути тут не нужен. А так же у тебя все еще хардкод элемента в тестовом методе, что недопустимо в дипломной работе.
Вынеси проверку, что у текущего элемента есть в локаторе "tab_tab_type_current" в step метод в PO классе. тогда это будет валидно.

2023-07-04 17:32 UTC, pavel-ulan commented on MainPageTests.java
> +        assertThat(newSauceText, is("Соусы"));
**надо исправить**
в Булках ты поправила, молодец, а тут тест все еще работает так же (точнее не работает).
Всегда проверяй на аналогичные ошибки всю работу

2023-07-04 17:32 UTC, pavel-ulan commented on MainPageTests.java
> +        assertThat(newFillingText, is("Начинки"));
**надо исправить**
что бы не потеряла - тут тоже

2023-07-04 17:32 UTC, pavel-ulan commented on src/main/java/praktikum/pageobject/MainPage.java
> +    private final By personalAccountButton = By.xpath("/html/body/div/div/header/nav/a/p"); // проверен
**надо исправить**
а этот локатор под определение "абсолютный путь" не подпадает разве?

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        // driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
не исправила =)

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
не вынесла =)

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
и тут

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
и тут

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/LoginPageTest.java
> +        assertThat(newAccountLinkText, is("Профиль"));
и тут

2023-07-04 17:32 UTC, pavel-ulan commented on src/test/java/praktikum/MainPageTests.java
> +        assertThat(newBreadText, is("Булки"));
У тебя обе ветки слились в одну. Часть тестов задублировалась, соответственно часть старых и часть новых. Разберись с коммитом пожалуйста.

2023-07-12 14:16 UTC, pavel-ulan approved these changes
Да, сейчас все действительно будет работать. 👍

2023-07-12 14:16 UTC, pavel-ulan commented on src/main/java/praktikum/pageobject/LoginPage.java
> +    private final By forgotPasswordButton = By.xpath("//*[text()='Восстановить пароль']"); // исправлен
👍

2023-07-12 14:16 UTC, pavel-ulan commented on src/main/java/praktikum/pageobject/MainPage.java
> +   // добавила методы для проверки, что таб не выбран
**хорошо**
Да, молодец 👍

2023-07-13 08:52 UTC, merged